const fs=require('fs'),vm=require('vm'),assert=require('assert'),path=require('path');
const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8'),scripts=[...html.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/g)].map(m=>m[1]);
const ctx=vm.createContext({console,Math});vm.runInContext(scripts[0],ctx);const THREE=ctx.THREE;
const noop=()=>{},gradient={addColorStop:noop},canvasContext=new Proxy({createLinearGradient:()=>gradient,createRadialGradient:()=>gradient,measureText:()=>({width:50})},{get:(o,k)=>o[k]||noop});
const elements=new Map();function element(id){if(!elements.has(id))elements.set(id,{value:id==='quality'?'high':'',style:{},classList:{add:noop,remove:noop,toggle:noop},appendChild:noop,addEventListener:noop,setAttribute:noop,blur:noop,getContext:()=>canvasContext});return elements.get(id);}
const document={getElementById:element,createElement:()=>({getContext:()=>canvasContext}),addEventListener:noop,activeElement:{blur:noop}},window={addEventListener:noop};
THREE.WebGLRenderer=class{constructor(){this.domElement=element('canvas');this.shadowMap={};this.info={render:{calls:0}};this.ratio=1;}setClearColor(){}setSize(){}setPixelRatio(x){this.ratio=x;}getPixelRatio(){return this.ratio;}render(){}};
let frame;const app=scripts[1].replace('window.__ride={','window.__test={traffic,peds,cityFixtures,streetBody,streetOverlap,StreetGrid,initializeStreet,updateStreet,animateCityCyclists,avenueHalf,streetHalf,streetDirection,getMounted:()=>mounted,getMountAge:()=>mountAge,reset,renderer};window.__ride={');
new Function('THREE','window','document','requestAnimationFrame','localStorage','innerWidth','innerHeight','devicePixelRatio','performance',app)(THREE,window,document,f=>frame=f,{getItem:()=>null,setItem:noop},1440,900,1,performance);
const ride=window.__ride,t=window.__test;assert(ride.state().running&&ride.state().practice,'opens directly in free city ride');assert.equal(ride.pose().mode,'STANDING BESIDE BIKE');assert.equal(t.traffic.filter(c=>c.cyclist).length,24);assert.equal(t.renderer.getPixelRatio(),1);
function audit(){const grid=new t.StreetGrid(),r={vv:0,pp:0,pv:0,fixtures:0};for(const f of t.cityFixtures)grid.add({...f});for(const b of [...t.traffic.map(c=>t.streetBody(c)),...t.peds.map(p=>t.streetBody(p,true))]){for(const o of grid.nearby(b))if(t.streetOverlap(b,o)){const fixture=t.cityFixtures.some(f=>f.owner===o.owner);r[fixture?'fixtures':b.ped&&o.ped?'pp':b.ped||o.ped?'pv':'vv']++;}grid.add(b);}return r;}
assert.deepStrictEqual(audit(),{vv:0,pp:0,pv:0,fixtures:0});
let maxBoneError=0;ride.keys.KeyW=true;for(let i=0;i<240;i++){ride.step(1/60);const p=ride.pose();for(const pair of p.legLengths)for(const l of pair)maxBoneError=Math.max(maxBoneError,Math.abs(l-.45));}assert(t.getMounted());assert(ride.state().speed>1.5,'launch gets moving');
const release=ride.state();ride.keys.KeyW=false;for(let i=0;i<60;i++)ride.step(1/60);const coast=ride.state();assert(coast.speed>0&&coast.pedal>release.pedal,'fixed gear continues pedaling after releasing W');
for(let i=0;i<60*30;i++)ride.step(1/60);assert(ride.state().speed<.05,'release eventually stops');assert(maxBoneError<.025,'mount leg lengths remain plausible');
console.log('Mechanics',JSON.stringify({launchSpeed:release.speed,afterRelease:coast.speed,finalSpeed:ride.state().speed,maxBoneError}));
// Render with real scene geometry and matrices, substituting only the GPU call.
frame(performance.now());
const seconds=Number(process.env.SIM_SECONDS||180),steps=seconds*60;let max={vv:0,pp:0,pv:0,fixtures:0},movement=0,crossings=0;const before=ride.state();
for(let i=0;i<steps;i++){const ps=t.peds.map(p=>p.dir),loc=t.traffic.map(c=>[c.g.position.x,c.g.position.z]);ride.step(i%47===0?1/30:1/60);const r=audit();for(const k in r){max[k]=Math.max(max[k],r[k]);assert.equal(r[k],0,k+' at '+i);}t.peds.forEach((p,j)=>{if(p.cross&&p.dir!==ps[j])crossings++;});t.traffic.forEach((c,j)=>{const d=Math.hypot(c.g.position.x-loc[j][0],c.g.position.z-loc[j][1]);if(d<5)movement+=d;});if(i%3600===0)console.log('simulation step',i);}
assert(movement>100,'traffic keeps moving');assert(t.peds.filter(p=>!p.cross).every(p=>{const av=[-160,0].sort((a,b)=>Math.abs(p.x-a)-Math.abs(p.x-b))[0];return Math.abs(p.x-av)>=15.5&&Math.abs(p.x-av)<=17.4;}),'ordinary walkers stay on sidewalks');
console.log('City',JSON.stringify({seconds:ride.state().elapsed-before.elapsed,max,movement,crossings,vehicles:t.traffic.length,cyclists:t.traffic.filter(c=>c.cyclist).length,regularWalkers:t.peds.filter(p=>!p.cross).length,jaywalkers:t.peds.filter(p=>p.jay).length,turns:ride.state().turns}));
